apiVersion: apps/v1
kind: Deployment
metadata:
  name: careercanvas-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: careercanvas-api
  template:
    metadata:
      labels:
        app: careercanvas-api
    spec:
      containers:
      - name: api
        image: careercanvas/jobs-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-url
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi