version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/careercanvas
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  scraper:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    command: python -m services.job_scraper.scheduler
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/careercanvas
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=careercanvas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: